name: terraform-apply

on:
  # Triggers the workflow on push request event but only for the "master" branch
  workflow_dispatch:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apply:
    # The type of runner that the job will run on
    name: Terraform apply
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: prod
      #TF_CLOUD_PROJECT: ByItsCover_PROD

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hashicorp - Terraform setup
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Runs a set of terraform commands using the runners shell
      - name: Terraform Init
        run: terraform init -backend-config=${{ env.ENVIRONMENT }}.hcl


      # - name: Terraform Workspace Create | Select
      #   run: terraform workspace select -or-create ${{ env.ENVIRONMENT }}

      - name: Terraform Validate
        run: |
          terraform fmt -recursive
          terraform validate
        continue-on-error: false

      - name: Terraform Apply
        run: |
          terraform apply \
            -var-file=variables/${{ env.ENVIRONMENT }}.tfvars \
            -var="tfc_aws_plan_role=${{ secrets.TFC_AWS_PLAN_ROLE_ARN }}" \
            -var="tfc_aws_apply_role=${{ secrets.TFC_AWS_APPLY_ROLE_ARN }}"
